services:
  mysql:
    image: mysql:8.0.38
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=investmentdb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

